name: pytmod
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - pip
  - numpy
  - scipy
  - matplotlib
  - scikit-image
  # FEM dependencies (conda-installed)
  - fenics-dolfinx>=0.9.0
  - petsc=*=complex*
