# Authors: Benjamin Vial
# This file is part of pytmod
# License: GPLv3
# See the documentation at bvial.info/pytmod


"""
Scattering from a Time-Modulated Slab
=====================================

This example demonstrates the scattering of electromagnetic waves from a
slab of time-modulated material. We compute the reflection and transmission
coefficients, including frequency sidebands generated by the temporal modulation.

This reproduces results from :cite:t:`zurita-sanchez2009`.
"""

# %%
# Imports and setup
# -----------------
# We begin by importing the necessary packages.

from __future__ import annotations

import matplotlib.pyplot as plt
import numpy as np

import pytmod as pm

# %%
# Background
# ----------
# When a plane wave interacts with a time-modulated slab, the scattered field
# contains not only the incident frequency but also sidebands at
# :math:`\omega + n\Omega` (Floquet harmonics), where :math:`\Omega` is the
# modulation frequency and :math:`n` is an integer.
#
# The scattering problem is solved by:
#
# 1. Finding the Floquet eigenmodes of the time-modulated material
# 2. Matching boundary conditions at the slab interfaces
# 3. Solving for the reflected and transmitted field amplitudes


# %%
# Problem parameters
# ------------------
# We define the material and geometry parameters for the slab:
#
# - Background permittivity :math:`\epsilon_0 = 5.25`
# - Modulation frequency :math:`\Omega = 1`
# - Floquet truncation with ``Npad = 5`` (11 harmonics total)
# - Frequency range :math:`0 \leq \omega \leq \Omega`

# Material parameters
eps0 = 5.25  # Background permittivity
Omega = 1.0  # Modulation frequency
Npad = 5  # Floquet truncation padding

# Frequency range for dispersion calculation
Nomega = 500
omegas = np.linspace(0, 1 * Omega, Nomega)


def get_eps_fourier(deps):
    """
    Generate Fourier coefficients for sinusoidal modulation.

    Parameters
    ----------
    deps : float
        Modulation amplitude Δε

    Returns
    -------
    list
        Fourier coefficients [ε₋₁, ε₀, ε₊₁]
    """
    return [
        -deps / (2 * 1j),  # ε₋₁ = -iΔε/2
        eps0,  # ε₀ (background)
        deps / (2 * 1j),  # ε₊₁ = +iΔε/2
    ]


# %%
# Figure 3: Dispersion Relations
# ------------------------------
# We first examine the dispersion relation :math:`k(\omega)` for different
# modulation amplitudes. The dispersion curves show how the wavenumber varies
# with frequency in the time-modulated medium.
#
# Three modulation strengths are considered:
# - Weak modulation: :math:`\Delta\epsilon = 0.085`
# - Moderate modulation: :math:`\Delta\epsilon = 0.85`
# - Strong modulation: :math:`\Delta\epsilon = 3.4`

fig3, ax3 = plt.subplots(3, 1, figsize=(6, 10))

deps_values = [0.085, 0.85, 3.4]

for i, deps in enumerate(deps_values):
    eps_fourier = get_eps_fourier(deps)
    mat = pm.Material(eps_fourier, Omega, Npad)

    # Solve for eigenvalues at each frequency
    kns, ens = mat.eigensolve(omegas, sign=False)

    # Plot dispersion curves (normalized)
    ax3[i].plot(
        kns.T.real / eps0**0.5,
        omegas.real / Omega,
        ".",
        color="#5000ca",
        markersize=3,
        markeredgewidth=0,
        label=f"$\\Delta\\epsilon = {deps}$",
    )
    ax3[i].set_xlim(0, 3)
    ax3[i].set_ylim(0, 1)
    ax3[i].set_title(rf"$\Delta \epsilon = {deps}$", fontsize=12)
    ax3[i].grid(True, alpha=0.3)

fig3.supxlabel(r"Normalized wave vector $kc/(\Omega\sqrt{\epsilon_0})$", fontsize=12)
fig3.supylabel(r"Normalized frequency $\omega/\Omega$", fontsize=12)
fig3.suptitle("Dispersion Relations for Different Modulation Amplitudes", fontsize=14)
fig3.tight_layout()
plt.show()


# %%
# Figures 4-5: Transmission and Reflection Coefficients
# -----------------------------------------------------
# We now compute the scattering from a finite slab. An incident wave at
# frequency :math:`\omega_0` generates reflected and transmitted fields
# with sideband components.
#
# The scattering problem is solved by:
# 1. Computing the material eigenmodes
# 2. Building the boundary condition matrix
# 3. Solving for field coefficients inside and outside the slab
#
# We examine two normalized thicknesses:
# - Thin slab: :math:`L_N = 0.5`
# - Thick slab: :math:`L_N = 2.0`
#
# And two modulation amplitudes for comparison.

# Extended frequency range for scattering calculation
Nomega = 1500
omegas = np.linspace(0.0001, 10 + 0.00001 * Omega, Nomega)

# Sideband to visualize (0 = fundamental frequency)
Nharmo_plot = 0

fig4, ax4 = plt.subplots(2, 2, figsize=(10, 8))
fig5, ax5 = plt.subplots(2, 2, figsize=(10, 8))

for i, Ln in enumerate([0.5, 2]):
    for j, deps in enumerate([0.085, 0.85]):
        # Slab thickness (normalized)
        L = Ln / eps0**0.5 / Omega

        # Create material and slab
        eps_fourier = get_eps_fourier(deps)
        mat = pm.Material(eps_fourier, Omega, Npad)
        slab = pm.Slab(mat, L)

        # Compute eigenmodes
        kns, ens = mat.eigensolve(omegas)

        # Build and solve the scattering matrix
        matrix_slab = slab.build_matrix(omegas, kns, ens)
        Eis = slab.init_incident_field(omegas)
        Ei0 = 1  # Incident field amplitude
        Eis[mat.Nh] = Ei0
        rhs_slab = slab.build_rhs(omegas, Eis)
        solution = slab.solve(matrix_slab, rhs_slab)

        # Extract reflection and transmission coefficients
        Eslab_plus, Eslab_minus, Er, Et = slab.extract_coefficients(
            solution, Eis, kns, ens
        )
        rn = Er / Ei0
        tn = Et / Ei0

        # Select the harmonic to plot
        imode = mat.Nh + Nharmo_plot

        # Plot magnitudes (Figure 4)
        r_mag = np.abs(rn[imode])
        t_mag = np.abs(tn[imode])
        ax4[i, j].plot(omegas, t_mag, "-", color="#5000ca", label=r"$|t|$")
        ax4[i, j].plot(omegas, r_mag, "-", color="#e49649", label=r"$|r|$")
        ax4[i, j].set_title(
            rf"$L_N = {Ln}, n = {Nharmo_plot}, \Delta\epsilon = {deps}$"
        )
        ax4[i, j].set_ylim(0)
        ax4[i, j].set_xlim(0, 10)
        ax4[i, j].grid(True, alpha=0.3)

        # Plot phases (Figure 5)
        r_phase = np.angle(rn[imode]) / np.pi
        t_phase = np.angle(tn[imode]) / np.pi
        ax5[i, j].plot(omegas, t_phase, "-", color="#5000ca", label=r"$\arg(t)/\pi$")
        ax5[i, j].plot(omegas, r_phase, "-", color="#e49649", label=r"$\arg(r)/\pi$")
        ax5[i, j].set_title(
            rf"$L_N = {Ln}, n = {Nharmo_plot}, \Delta\epsilon = {deps}$"
        )
        ax5[i, j].set_ylim(-1, 1)
        ax5[i, j].set_xlim(0, 10)
        ax5[i, j].grid(True, alpha=0.3)

ax4[0, 1].legend(loc="upper right")
ax5[0, 1].legend(loc="upper right")
fig4.supxlabel(r"Normalized frequency $\omega_0/\Omega$", fontsize=12)
fig4.supylabel("Magnitude", fontsize=12)
fig5.supxlabel(r"Normalized frequency $\omega_0/\Omega$", fontsize=12)
fig5.supylabel(r"Phase ($\times\pi$)", fontsize=12)
fig4.suptitle(
    "Transmission and Reflection Magnitudes (Fundamental Harmonic)", fontsize=14
)
fig5.suptitle("Transmission and Reflection Phases (Fundamental Harmonic)", fontsize=14)
fig4.tight_layout()
fig5.tight_layout()
plt.show()


# %%
# Figures 6-7: First-Order Sidebands
# ----------------------------------
# The time modulation generates sidebands at frequencies :math:`\omega \pm \Omega`.
# Here we examine the first-order sidebands (:math:`n = \pm 1`) for a weakly
# modulated slab (:math:`\Delta\epsilon = 0.085`).
#
# We compare:
# - Thin slab (:math:`L_N = 0.5`)
# - Thick slab (:math:`L_N = 8`)

deps = 0.085  # Weak modulation

fig6, ax6 = plt.subplots(2, 2, figsize=(10, 8))
fig7, ax7 = plt.subplots(2, 2, figsize=(10, 8))

for i, Ln in enumerate([0.5, 8]):
    L = Ln / eps0**0.5 / Omega
    eps_fourier = get_eps_fourier(deps)
    mat = pm.Material(eps_fourier, Omega, Npad)
    slab = pm.Slab(mat, L)

    # Compute scattering
    kns, ens = mat.eigensolve(omegas)
    matrix_slab = slab.build_matrix(omegas, kns, ens)
    Eis = slab.init_incident_field(omegas)
    Ei0 = 1
    Eis[mat.Nh] = Ei0
    rhs_slab = slab.build_rhs(omegas, Eis)
    solution = slab.solve(matrix_slab, rhs_slab)

    Eslab_plus, Eslab_minus, Er, Et = slab.extract_coefficients(solution, Eis, kns, ens)
    rn = Er / Ei0
    tn = Et / Ei0

    for j, Nharmo_plot in enumerate([1, -1]):
        imode = mat.Nh + Nharmo_plot

        # Magnitudes (Figure 6)
        r_mag = np.abs(rn[imode])
        t_mag = np.abs(tn[imode])
        ax6[i, j].plot(omegas, t_mag, "-", color="#5000ca", label=r"$|t|$")
        ax6[i, j].plot(omegas, r_mag, "-", color="#e49649", label=r"$|r|$")
        ax6[i, j].set_title(
            rf"$L_N = {Ln}, n = {Nharmo_plot}, \Delta\epsilon = {deps}$"
        )
        ax6[i, j].set_ylim(0)
        ax6[i, j].set_xlim(0, 10)
        ax6[i, j].grid(True, alpha=0.3)

        # Phases (Figure 7)
        r_phase = np.angle(rn[imode]) / np.pi
        t_phase = np.angle(tn[imode]) / np.pi
        ax7[i, j].plot(omegas, t_phase, "-", color="#5000ca", label=r"$\arg(t)/\pi$")
        ax7[i, j].plot(omegas, r_phase, "-", color="#e49649", label=r"$\arg(r)/\pi$")
        ax7[i, j].set_title(
            rf"$L_N = {Ln}, n = {Nharmo_plot}, \Delta\epsilon = {deps}$"
        )
        ax7[i, j].set_ylim(-1, 1)
        xmax = 2 if Ln == 8 else 10
        ax7[i, j].set_xlim(0, xmax)
        ax7[i, j].grid(True, alpha=0.3)

        # Hide x-axis labels for top row
        if i == 0:
            ax6[i, j].set_xticklabels([])
            ax7[i, j].set_xticklabels([])

ax6[0, 1].legend(loc="upper right")
ax7[0, 1].legend(loc="upper right")
fig6.supxlabel(r"Normalized frequency $\omega_0/\Omega$", fontsize=12)
fig6.supylabel("Magnitude", fontsize=12)
fig7.supxlabel(r"Normalized frequency $\omega_0/\Omega$", fontsize=12)
fig7.supylabel(r"Phase ($\times\pi$)", fontsize=12)
fig6.suptitle("First-Order Sideband Scattering (n = ±1)", fontsize=14)
fig7.suptitle("First-Order Sideband Phases (n = ±1)", fontsize=14)
fig6.tight_layout()
fig7.tight_layout()
plt.show()


# %%
# Figures 8-9: Higher-Order Sidebands
# -----------------------------------
# For stronger modulation (:math:`\Delta\epsilon = 0.85`), higher-order
# sidebands become significant. Here we examine sidebands up to second order
# (:math:`n = \pm 2`) for both thin and thick slabs.

deps = 0.85  # Stronger modulation

fig8, ax8 = plt.subplots(4, 2, figsize=(10, 12))
fig9, ax9 = plt.subplots(4, 2, figsize=(10, 12))

for j, Ln in enumerate([0.5, 8]):
    L = Ln / eps0**0.5 / Omega
    eps_fourier = get_eps_fourier(deps)
    mat = pm.Material(eps_fourier, Omega, Npad)
    slab = pm.Slab(mat, L)

    # Compute scattering
    kns, ens = mat.eigensolve(omegas)
    matrix_slab = slab.build_matrix(omegas, kns, ens)
    Eis = slab.init_incident_field(omegas)
    Ei0 = 1
    Eis[mat.Nh] = Ei0
    rhs_slab = slab.build_rhs(omegas, Eis)
    solution = slab.solve(matrix_slab, rhs_slab)

    Eslab_plus, Eslab_minus, Er, Et = slab.extract_coefficients(solution, Eis, kns, ens)
    rn = Er / Ei0
    tn = Et / Ei0

    for i, Nharmo_plot in enumerate([1, -1, 2, -2]):
        imode = mat.Nh + Nharmo_plot

        # Magnitudes (Figure 8)
        r_mag = np.abs(rn[imode])
        t_mag = np.abs(tn[imode])
        ax8[i, j].plot(omegas, t_mag, "-", color="#5000ca", label=r"$|t|$")
        ax8[i, j].plot(omegas, r_mag, "-", color="#e49649", label=r"$|r|$")
        ax8[i, j].set_title(
            rf"$L_N = {Ln}, n = {Nharmo_plot}, \Delta\epsilon = {deps}$"
        )
        ax8[i, j].set_ylim(0)
        ax8[i, j].set_xlim(0, 10)
        ax8[i, j].grid(True, alpha=0.3)

        # Phases (Figure 9)
        r_phase = np.angle(rn[imode]) / np.pi
        t_phase = np.angle(tn[imode]) / np.pi
        ax9[i, j].plot(omegas, t_phase, "-", color="#5000ca", label=r"$\arg(t)/\pi$")
        ax9[i, j].plot(omegas, r_phase, "-", color="#e49649", label=r"$\arg(r)/\pi$")
        ax9[i, j].set_title(
            rf"$L_N = {Ln}, n = {Nharmo_plot}, \Delta\epsilon = {deps}$"
        )
        ax9[i, j].set_ylim(-1, 1)
        xmax = 2 if Ln == 8 else 10
        ax9[i, j].set_xlim(0, xmax)
        ax9[i, j].grid(True, alpha=0.3)

        # Hide x-axis labels except for bottom row
        if i < 3:
            ax8[i, j].set_xticklabels([])
            ax9[i, j].set_xticklabels([])

ax8[1, 0].legend(loc="upper right")
ax9[1, 0].legend(loc="upper right")
fig8.supxlabel(r"Normalized frequency $\omega_0/\Omega$", fontsize=12)
fig8.supylabel("Magnitude", fontsize=12)
fig9.supxlabel(r"Normalized frequency $\omega_0/\Omega$", fontsize=12)
fig9.supylabel(r"Phase ($\times\pi$)", fontsize=12)
fig8.suptitle("Higher-Order Sideband Scattering (n = ±1, ±2)", fontsize=14)
fig9.suptitle("Higher-Order Sideband Phases (n = ±1, ±2)", fontsize=14)
fig8.tight_layout()
fig9.tight_layout()
plt.show()


# %%
# Summary
# -------
# This example demonstrated:
#
# 1. **Dispersion relations** in time-modulated materials showing how the
#    band structure changes with modulation amplitude.
#
# 2. **Fundamental harmonic scattering** showing reflection and transmission
#    spectra for different slab thicknesses and modulation strengths.
#
# 3. **Sideband generation** - the time modulation creates scattered fields
#    at frequencies shifted by multiples of the modulation frequency.
#
# 4. **Thickness dependence** - comparing thin and thick slabs shows how
#    interference effects and resonances depend on the optical path length.
#
# These results are consistent with the Floquet scattering theory presented
# in Zurita-Sáncez et al. (2009), demonstrating how temporal modulation can
# be used to control light propagation and generate new frequency components.
